#!/usr/bin/env bash

set -e

SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE:-$0}")")

### Script arg parse is done by code generated by Argbash and is located in lib/run-test-arg-parser.sh
# shellcheck source=/dev/null
source "${SCRIPT_DIR}/lib/run-test-arg-parser.sh"

function log() {
    if [[ "$1" == "" ]]; then
        echo "$1"
    else
        echo "[$(date "+%Y-%m-%d %H:%M:%S %z")] - $1"
    fi
}

# shellcheck disable=SC2154 
if [[ "${_arg_debug}" == "on" ]]; then
    set -x
fi

if [[ -z "${_arg_kubeconfig}" ]]; then
    export KUBE_CONFIG="${KUBECONFIG:-${HOME}/.kube/config}"
else
    export KUBE_CONFIG="${_arg_kubeconfig}"
fi

log "Value of --debug: $_arg_debug"
# shellcheck disable=SC2154 
log "Value of --image-namespace: $_arg_image_namespace"
# shellcheck disable=SC2154 
log "Value of --image-tag: $_arg_image_tag"
# shellcheck disable=SC2154 
log "Value of --make-target: $_arg_make_target"
# shellcheck disable=SC2154 
log "Value of --namespace: $_arg_namespace"
log "Value of --make-envvar: ${_arg_make_envvar[*]}"
log "Value of --kubeconfig: $_arg_kubeconfig"
# shellcheck disable=SC2154 
log "Value of --test-completion-wait-check: $_arg_test_completion_wait_check"

export NAMESPACE="${_arg_namespace}"
export IMAGE="quay.io/${_arg_image_namespace}/claire:${_arg_image_tag}"

if [[ "${_arg_image_tag}" == "amq-broker"* ]]; then
    log "amq-broker image tag detected, using file Makefile.downstream as makefile"
    MAKE_TARGET="-f Makefile.downstream "
fi
MAKE_TARGET+="${_arg_make_target}"
export MAKE_TARGET


log ""
COMMIT_ID=$(git rev-parse HEAD || echo "fail to get commit id. It was not found or not in a git repo")
log "Using $0 from git commit id: ${COMMIT_ID}"
log ""

log ""
log "Creating Namespace ${NAMESPACE}"
yq e '.metadata.name = strenv(NAMESPACE)' "${SCRIPT_DIR}/yaml/010-namespace.yaml" | tee >(kubectl apply -f -)
sleep 5

log ""
log "Creating secret for kubeconfig from ${KUBE_CONFIG}"
mkdir -p /tmp/claire.$$ 
cp "${KUBE_CONFIG}" /tmp/claire.$$/config
kubectl -n "${NAMESPACE}" create secret generic claire-kubeconfig --from-file /tmp/claire.$$/config || true      
sleep 5

log ""
log "Creating config map for run script"
yq '(.metadata.namespace = strenv(NAMESPACE)) | (.data."run.sh" |= envsubst)' "${SCRIPT_DIR}/yaml/020-configmap.yaml" | tee >(kubectl apply -f -)
sleep 5

log ""
log "Creating test suite pod"
cp "${SCRIPT_DIR}/yaml/030-pod.yaml" "${SCRIPT_DIR}/yaml/030-pod.yaml.$$"
_arg_make_envvar+=('MVN_TEST_ADDITIONAL_ARGS=-Dfailsafe.rerunFailingTestsCount=2' 'TEST_LOG_LEVEL=DEBUG' 'MVN_ADDITIONAL_PARAMS="--offline"' 'OLM_USE_DEFAULT_CHANNEL=true')
if [[ "${#_arg_make_envvar[@]}" -gt 0  ]]; then
    for i in "${_arg_make_envvar[@]}"; do
        KEY="$(echo "${i}" | cut -d"=" -f1)"
        export KEY;
        VALUE="$(echo "${i}" | cut -d"=" -f2-)"
        export VALUE;
        yq -i e '(.spec.containers |=  map(select(.name == "claire-test-suite").env += [{"name": strenv(KEY), "value": strenv(VALUE)}]))' "${SCRIPT_DIR}/yaml/030-pod.yaml.$$"
    done
fi
yq -i e '(.metadata.namespace = strenv(NAMESPACE))' "${SCRIPT_DIR}/yaml/030-pod.yaml.$$"
yq -i e '(.spec.containers[].image = strenv(IMAGE))' "${SCRIPT_DIR}/yaml/030-pod.yaml.$$"
yq -i e '.spec.containers[].env[] |= select(.name == "CONTAINER_IMAGE") |= .value = strenv(IMAGE)' "${SCRIPT_DIR}/yaml/030-pod.yaml.$$"
tee >(kubectl apply -f -) < "${SCRIPT_DIR}/yaml/030-pod.yaml.$$"
rm -rf "${SCRIPT_DIR}/yaml/030-pod.yaml.$$"
sleep 5

log ""
log "Waiting claire-test-suite pod reach Running state"
set +e
if kubectl wait -n "${NAMESPACE}" --for=jsonpath='{.status.phase}'='Running' pod/claire-test-suite --timeout=300s ; then
    log ""
    log "Waiting execution to finish"
    set +e
    while ! kubectl -n "${NAMESPACE}" exec claire-test-suite -- /bin/ls /app/test-results/tests.execution.completed > /dev/null 2>&1; do
        log "Execution not completed. Waiting for ${_arg_test_completion_wait_check} seconds before check again"
        sleep "${_arg_test_completion_wait_check}"
    done
    set -e

    log ""
    log "Copying test results, logs and additional files to ${PWD}/test-results"
    mkdir -p "${PWD}/test-results/operator-suite"
    # shellcheck disable=SC2016
    kubectl exec -n "${NAMESPACE}" claire-test-suite -- bash -c 'tar cf - $(find /app/test-results /app/operator-suite/test-logs /app/operator-suite/test-tmp 2>/dev/null)' | tar --strip-components 2 -xf - -C test-results

    log ""
    log "Displaying logs"
    cat test-results/tests.execution.started
    cat test-results/tests.execution.log
    cat test-results/tests.execution.completed
else
    log "Error on getting claire-test-suite pod into Running state. Dumping logs"
    log ""
    log "Getting events"
    kubectl -n "${NAMESPACE}" get events
    log ""
    log "Gettings pod logs"
    kubectl -n "${NAMESPACE}" logs claire-test-suite
fi
set -e

log ""
log "Deleting Namespace ${NAMESPACE}"
yq e '.metadata.name = strenv(NAMESPACE)' "${SCRIPT_DIR}/yaml/010-namespace.yaml" | tee >(kubectl delete -f -)

